issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:rothandrew-octo-sts-testing/.*:issues
#claim_pattern:
#  workflow_ref: rothandrew-octo-sts-testing/.*
permissions:
  repository_projects: write
  organization_projects: write
#repositories: []
