issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:rothandrew-octo-sts-testing/test-repo:.*
claim_pattern:
  workflow_ref: rothandrew-octo-sts-testing/.*
permissions:
  pull_requests: write
repositories: []
