issuer: https://token.actions.githubusercontent.com
# Allow any repo in the "rothandrew-octo-sts-testing" org, but only workflows that use the "issues" event
subject_pattern: repo:rothandrew-octo-sts-testing/test-repo:.*
claim_pattern:
  workflow_ref: rothandrew-octo-sts-testing/.*

permissions:
  administration: write
  organization_administration: write
  projects: write

repositories: []
